repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args:
          [
            --fix,
            --extend-select,
            I,
            --per-file-ignores,
            test/test_rans_surrogate_example.py:E402,
          ]
        files: ^(src)/
      - id: ruff-format
        files: ^(src|test)/
